# Generated by Django 5.2.10 on 2026-05-16 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_messages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='convuser',
            name='is_live',
            field=models.BooleanField(default=False),
        ),
    ]
