# Generated by Django 5.2.10 on 2026-01-23 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_users', '0002_customuser_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='website',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
