# Generated by Django 5.2.10 on 2026-01-30 02:18

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_users', '0003_alter_customuser_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=750, scale=None, size=[600, 600], upload_to='avatars/'),
        ),
    ]
