# Generated by Django 5.2.10 on 2026-02-01 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_users', '0004_alter_customuser_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='darkmode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='notifications',
            field=models.BooleanField(default=True),
        ),
    ]
