# Generated by Django 5.2.10 on 2026-01-30 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_posts', '0003_alter_post_uuid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
    ]
