# Generated by Django 5.2.10 on 2026-04-28 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_posts', '0007_comment_likedcomment_comment_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='parent_reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='_posts.comment'),
        ),
    ]
