# Generated by Django 5.2.10 on 2026-05-03 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_posts', '0009_repost_post_reposts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-count', 'name'],
            },
        ),
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='posts', to='_posts.tag'),
        ),
    ]
