# Generated by Django 5.2.10 on 2026-05-16 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_posts', '0011_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.ImageField(blank=True, null=True, upload_to='posts/videos/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/'),
        ),
    ]
