# Generated by Django 5.2.10 on 2026-05-16 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_posts', '0012_post_video_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='posts/videos/'),
        ),
    ]
