# Generated by Django 5.2.10 on 2026-05-03 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_network', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'ordering': ['-created_at']},
        ),
    ]
